### ISSUE TITLE
저장소 네이밍

### ISSUE THREAD

**Issue by Ariyn** [rockpell/mit-games-algorithm#5]
mit-games가 공식 명칭인건 맞지만, 하이픈과 언더바가 섞여 있으니 네이밍이 조금 애매한것 같습니다.
mit-games's algorithm정도로 바꿔보면 어떨까요? (싱글 쿼트가 사용 가능한지는 모르겠습니다.)

**Comment by rockpell** [comment]
아쉽게도 '와 공백은 -로 대체되서 이상하게 보이더군요
우선 mit-games-algorithm으로 대체하는게 그나마 괜찮아보여 변경하였습니다.

**Comment by Ariyn** [comment]
감사합니다.
더 좋은 네이밍은 저도 고민하겠습니다.
