### ISSUE TITLE
subfolder의 문제.md를 README.md로 변환

### ISSUE THREAD

**Issue by Ariyn** [rockpell/mit-games-algorithm#6]
각 서브 폴더에 README.md를 만들면 그 폴더를 눌렀을때 github에서 바로 보여줍니다.
문제.md를 README.md로 변환하면 깃헙에서 보기 깔끔할것 같아요.

**Comment by rockpell** [comment]
좋은 의견 감사합니다.
반영하니 보기 편해졌습니다.
